PUT http://localhost:4000/iem/1/signature
Content-Type: application/json

{
  "primarySignature": "NEUTRAL",
  "bassScore": 0.5,
  "midsScore": 0.7,
  "trebleScore": 0.6,
  "description": "Balanced sound"
}

###